package com.calculadora

const val N0 = "0"
const val N1 = "1"
const val N2 = "2"
const val N3 = "3"
const val N4 = "4"
const val N5 = "5"
const val N6 = "6"
const val N7 = "7"
const val N8 = "8"
const val N9 = "9"
const val ponto = "."
const val sinal = "+/-"
const val subtracao = "-"
const val adicao ="+"
const val divisao = "÷"
const val multiplicacao = "×"
const val c = "AC"
const val back = "BACK"
const val igual = "="
const val error = "Error"